#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE="$HOME/.config/fruitude/auth.properties"
mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

banner "鮮果鋪會員 Google 登入與忘記密碼設定"

# ── 第一階段：建立 Google Cloud 專案及同意畫面 ──────────────────────────
stage "Google Cloud 專案與 OAuth 同意畫面"
say "先設定 Google 登入會顯示的應用程式資訊與測試使用者。"
open_url "https://console.cloud.google.com/auth/overview"
step "選擇既有專案，或建立一個專案。"
step "進入 Google Auth Platform，依畫面完成 Branding（品牌資訊）與 Audience（目標對象）。"
step "若應用程式處於測試狀態，請在 Test users 加入要測試登入的 Google 信箱。"
note "Google 後台名稱可能略有不同，請找 Google Auth Platform 的 Branding、Audience 與 Clients。"
pause "完成 OAuth 同意畫面後，按 Enter 繼續。"

# ── 第二階段：建立 OAuth 用戶端 ─────────────────────────────────────────
stage "建立 Web OAuth 用戶端"
say "建立網站用戶端，並把本專案目前使用的網址填入 Google Cloud。"
open_url "https://console.cloud.google.com/auth/clients"
step "按 Create client，Application type 選 Web application。"
step "Authorized JavaScript origins 新增：http://localhost:8081"
step "Authorized redirect URIs 新增：http://localhost:8081/TKA102G2/api/members/google/callback"
step "建立後複製 Client ID；Client secret 請勿貼到聊天或提交到 Git。"
ask GOOGLE_CLIENT_ID "貼上 Client ID："
ask_secret GOOGLE_CLIENT_SECRET "貼上 Client secret（輸入時不會顯示）："
if [[ -z "$GOOGLE_CLIENT_ID" || -z "$GOOGLE_CLIENT_SECRET" ]]; then
  warn "Client ID 與 Client secret 都不能空白。"
  exit 1
fi
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
write_env GOOGLE_REDIRECT_URI "http://localhost:8081/TKA102G2/api/members/google/callback"
write_env APP_PUBLIC_BASE_URL "http://localhost:8081/TKA102G2"

# ── 第三階段：建立 Gmail 應用程式密碼 ───────────────────────────────────
stage "Gmail 兩步驟驗證與應用程式密碼"
say "忘記密碼郵件會由這個 Gmail 帳號寄出。"
open_url "https://myaccount.google.com/apppasswords"
step "若尚未開啟兩步驟驗證，請先到 Google 帳戶的安全性頁面啟用。"
step "建立一組應用程式密碼，名稱可填「鮮果鋪會員密碼重設」。"
step "複製 Google 顯示的 16 位應用程式密碼；不要使用一般 Gmail 登入密碼。"
ask MAIL_USERNAME "輸入寄信使用的完整 Gmail 地址："
ask_secret MAIL_APP_PASSWORD "貼上 Gmail 應用程式密碼（輸入時不會顯示）："
MAIL_APP_PASSWORD="${MAIL_APP_PASSWORD//[[:space:]]/}"
if [[ "$MAIL_USERNAME" != *@gmail.com || -z "$MAIL_APP_PASSWORD" ]]; then
  warn "請輸入完整 Gmail 地址與非空白的應用程式密碼。"
  exit 1
fi
write_env MAIL_USERNAME "$MAIL_USERNAME"
write_env MAIL_APP_PASSWORD "$MAIL_APP_PASSWORD"
write_env MAIL_FROM "$MAIL_USERNAME"
chmod 600 "$ENV_FILE"

# ── 第四階段：重新啟動並驗證 ───────────────────────────────────────────
stage "重新啟動 Tomcat 並驗證"
say "設定已安全存到 ${ENV_FILE}，權限為僅目前使用者可讀寫。"
warn "Port 保持 8081，不需要修改 Eclipse 或 Tomcat 的 Port。"
step "回到 Eclipse Servers，停止目前的 Tomcat，再重新啟動，讓 Spring 載入新設定。"
pause "Tomcat 已重新啟動並看到啟動完成訊息後，按 Enter 執行檢查。"

AUTHORIZE_URL="http://localhost:8081/TKA102G2/api/members/google/authorize"
if HEADERS=$(curl -sS --max-time 10 -D - -o /dev/null "$AUTHORIZE_URL" 2>/dev/null); then
  if printf '%s' "$HEADERS" | grep -qi '^Location: https://accounts.google.com/'; then
    printf '  %s✓ Google 登入已正確導向 Google%s\n' "$GREEN" "$RESET"
  else
    warn "伺服器有回應，但尚未導向 Google。請確認剛才貼上的 OAuth 憑證後再執行一次。"
  fi
else
  warn "目前連不到 Tomcat；請確認 Eclipse 中的 Tomcat 已在 8081 啟動。"
fi

open_url "http://localhost:8081/TKA102G2/front/about/login/"
step "按「使用 Google 登入」，確認會開啟 Google 帳戶選擇畫面。"
step "回登入頁按「忘記密碼」，輸入資料庫中既有會員的 Gmail，確認收到重設信。"
note "Google 登入只接受資料庫中已存在、且 Email 與 Google 驗證信箱相同的會員。"
pause "完成登入與收信測試後，按 Enter 顯示摘要。"

finish
